// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Condiments"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Confections"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Dairy Products"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Grains/Cereals"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Meat/Poultry"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Produce"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Seafood"
                        });
                });

            modelBuilder.Entity("Repository.entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            ProductName = "Generic Concrete Pants",
                            UnitPrice = 93.745864516281427m,
                            UnitsInStock = 81
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            ProductName = "Generic Soft Table",
                            UnitPrice = 84.5015003370064m,
                            UnitsInStock = 69
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ProductName = "Refined Metal Computer",
                            UnitPrice = 9.4216664909329084m,
                            UnitsInStock = 33
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 8,
                            ProductName = "Incredible Frozen Hat",
                            UnitPrice = 31.125724186177576m,
                            UnitsInStock = 24
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ProductName = "Small Frozen Gloves",
                            UnitPrice = 29.669678882940403m,
                            UnitsInStock = 79
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ProductName = "Incredible Soft Chips",
                            UnitPrice = 7.2806778613541809m,
                            UnitsInStock = 72
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            ProductName = "Practical Wooden Sausages",
                            UnitPrice = 36.034087564910665m,
                            UnitsInStock = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            ProductName = "Rustic Plastic Ball",
                            UnitPrice = 87.651537526680643m,
                            UnitsInStock = 75
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            ProductName = "Handcrafted Soft Bike",
                            UnitPrice = 2.7900770588821549m,
                            UnitsInStock = 57
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            ProductName = "Incredible Wooden Chair",
                            UnitPrice = 34.868422772214085m,
                            UnitsInStock = 66
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ProductName = "Awesome Concrete Table",
                            UnitPrice = 37.089681604857694m,
                            UnitsInStock = 12
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ProductName = "Small Rubber Sausages",
                            UnitPrice = 63.134829886723858m,
                            UnitsInStock = 58
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            ProductName = "Tasty Plastic Sausages",
                            UnitPrice = 86.387573789563771m,
                            UnitsInStock = 86
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ProductName = "Awesome Soft Soap",
                            UnitPrice = 98.321036561043724m,
                            UnitsInStock = 20
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            ProductName = "Generic Plastic Pants",
                            UnitPrice = 64.15389404316685m,
                            UnitsInStock = 36
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            ProductName = "Incredible Wooden Salad",
                            UnitPrice = 81.610069445610562m,
                            UnitsInStock = 92
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            ProductName = "Rustic Steel Soap",
                            UnitPrice = 57.0999467767618m,
                            UnitsInStock = 95
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            ProductName = "Ergonomic Fresh Ball",
                            UnitPrice = 32.49940317449266m,
                            UnitsInStock = 69
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            ProductName = "Practical Rubber Salad",
                            UnitPrice = 8.4976081016052502m,
                            UnitsInStock = 63
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            ProductName = "Incredible Concrete Pizza",
                            UnitPrice = 91.128894529990294m,
                            UnitsInStock = 16
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            ProductName = "Rustic Granite Car",
                            UnitPrice = 81.453543864645358m,
                            UnitsInStock = 84
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            ProductName = "Practical Plastic Towels",
                            UnitPrice = 18.062057744062309m,
                            UnitsInStock = 58
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            ProductName = "Fantastic Soft Chair",
                            UnitPrice = 39.780917374909303m,
                            UnitsInStock = 77
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            ProductName = "Sleek Concrete Pants",
                            UnitPrice = 5.0068998439961887m,
                            UnitsInStock = 17
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            ProductName = "Intelligent Fresh Table",
                            UnitPrice = 18.04434137572969m,
                            UnitsInStock = 89
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            ProductName = "Practical Granite Car",
                            UnitPrice = 73.798433220328255m,
                            UnitsInStock = 94
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            ProductName = "Fantastic Plastic Gloves",
                            UnitPrice = 44.617025335298041m,
                            UnitsInStock = 34
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            ProductName = "Tasty Steel Cheese",
                            UnitPrice = 7.2417719993065822m,
                            UnitsInStock = 14
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            ProductName = "Practical Frozen Mouse",
                            UnitPrice = 87.848276236921045m,
                            UnitsInStock = 8
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            ProductName = "Small Wooden Bacon",
                            UnitPrice = 95.169444920196679m,
                            UnitsInStock = 81
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            ProductName = "Refined Frozen Pants",
                            UnitPrice = 89.867558293374421m,
                            UnitsInStock = 5
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            ProductName = "Practical Metal Tuna",
                            UnitPrice = 65.492237537634412m,
                            UnitsInStock = 71
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 8,
                            ProductName = "Refined Concrete Soap",
                            UnitPrice = 43.87028055740056m,
                            UnitsInStock = 85
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            ProductName = "Refined Wooden Gloves",
                            UnitPrice = 33.928189264610596m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            ProductName = "Generic Frozen Chicken",
                            UnitPrice = 62.319493568781811m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            ProductName = "Licensed Metal Mouse",
                            UnitPrice = 47.902246164446662m,
                            UnitsInStock = 3
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            ProductName = "Rustic Cotton Pizza",
                            UnitPrice = 50.899655688956524m,
                            UnitsInStock = 5
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            ProductName = "Handcrafted Plastic Tuna",
                            UnitPrice = 33.468991028031844m,
                            UnitsInStock = 74
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            ProductName = "Awesome Rubber Chair",
                            UnitPrice = 43.357743370752238m,
                            UnitsInStock = 39
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            ProductName = "Sleek Cotton Pizza",
                            UnitPrice = 61.978287894238891m,
                            UnitsInStock = 67
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            ProductName = "Sleek Metal Bike",
                            UnitPrice = 8.5893350561943805m,
                            UnitsInStock = 69
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            ProductName = "Fantastic Steel Sausages",
                            UnitPrice = 57.712615111704475m,
                            UnitsInStock = 15
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            ProductName = "Awesome Soft Gloves",
                            UnitPrice = 56.904638918870368m,
                            UnitsInStock = 21
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            ProductName = "Sleek Cotton Tuna",
                            UnitPrice = 98.826517668021472m,
                            UnitsInStock = 25
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            ProductName = "Intelligent Rubber Pants",
                            UnitPrice = 79.976124619530886m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            ProductName = "Practical Metal Fish",
                            UnitPrice = 14.499583964732107m,
                            UnitsInStock = 23
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            ProductName = "Tasty Rubber Chicken",
                            UnitPrice = 93.18403252405765m,
                            UnitsInStock = 44
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            ProductName = "Incredible Wooden Bacon",
                            UnitPrice = 1.21991794609166173m,
                            UnitsInStock = 12
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            ProductName = "Gorgeous Wooden Sausages",
                            UnitPrice = 36.557422978105567m,
                            UnitsInStock = 99
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            ProductName = "Unbranded Steel Car",
                            UnitPrice = 12.668133018173698m,
                            UnitsInStock = 14
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            ProductName = "Licensed Cotton Car",
                            UnitPrice = 63.261828430043374m,
                            UnitsInStock = 48
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            ProductName = "Practical Steel Chicken",
                            UnitPrice = 34.033452473240164m,
                            UnitsInStock = 5
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            ProductName = "Awesome Plastic Chicken",
                            UnitPrice = 8.6491299395561941m,
                            UnitsInStock = 74
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 1,
                            ProductName = "Intelligent Concrete Bike",
                            UnitPrice = 98.334000264519964m,
                            UnitsInStock = 30
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            ProductName = "Fantastic Metal Hat",
                            UnitPrice = 94.460491012476115m,
                            UnitsInStock = 16
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            ProductName = "Intelligent Frozen Bike",
                            UnitPrice = 68.738779627274404m,
                            UnitsInStock = 57
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            ProductName = "Unbranded Metal Salad",
                            UnitPrice = 29.401686006759208m,
                            UnitsInStock = 60
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            ProductName = "Gorgeous Metal Shirt",
                            UnitPrice = 66.622477522887406m,
                            UnitsInStock = 67
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            ProductName = "Licensed Granite Tuna",
                            UnitPrice = 99.471424667433598m,
                            UnitsInStock = 53
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            ProductName = "Incredible Granite Fish",
                            UnitPrice = 82.770346544010553m,
                            UnitsInStock = 45
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            ProductName = "Rustic Cotton Computer",
                            UnitPrice = 49.838805684481285m,
                            UnitsInStock = 89
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 8,
                            ProductName = "Small Soft Pants",
                            UnitPrice = 9.8751552646436317m,
                            UnitsInStock = 8
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 8,
                            ProductName = "Intelligent Steel Mouse",
                            UnitPrice = 70.945822694162404m,
                            UnitsInStock = 88
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 2,
                            ProductName = "Handcrafted Plastic Pizza",
                            UnitPrice = 7.3683316321430905m,
                            UnitsInStock = 99
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            ProductName = "Awesome Fresh Cheese",
                            UnitPrice = 23.137455341037817m,
                            UnitsInStock = 84
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 5,
                            ProductName = "Licensed Fresh Mouse",
                            UnitPrice = 50.325166721073232m,
                            UnitsInStock = 89
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 5,
                            ProductName = "Intelligent Frozen Car",
                            UnitPrice = 50.337573460436602m,
                            UnitsInStock = 85
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            ProductName = "Sleek Metal Chicken",
                            UnitPrice = 87.826120349793418m,
                            UnitsInStock = 36
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 4,
                            ProductName = "Licensed Frozen Salad",
                            UnitPrice = 26.725957649035534m,
                            UnitsInStock = 58
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 5,
                            ProductName = "Awesome Wooden Tuna",
                            UnitPrice = 89.709505552999243m,
                            UnitsInStock = 76
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 7,
                            ProductName = "Unbranded Granite Pants",
                            UnitPrice = 31.268103366342952m,
                            UnitsInStock = 12
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 5,
                            ProductName = "Fantastic Concrete Chicken",
                            UnitPrice = 51.314142424576888m,
                            UnitsInStock = 54
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 5,
                            ProductName = "Rustic Cotton Cheese",
                            UnitPrice = 49.461366649031083m,
                            UnitsInStock = 19
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 4,
                            ProductName = "Licensed Soft Chips",
                            UnitPrice = 25.584123080022715m,
                            UnitsInStock = 4
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 2,
                            ProductName = "Generic Metal Pants",
                            UnitPrice = 68.179386828856753m,
                            UnitsInStock = 65
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 3,
                            ProductName = "Handmade Fresh Pizza",
                            UnitPrice = 51.705675088335784m,
                            UnitsInStock = 98
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 3,
                            ProductName = "Small Steel Keyboard",
                            UnitPrice = 96.22412591435722m,
                            UnitsInStock = 13
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 5,
                            ProductName = "Handmade Concrete Salad",
                            UnitPrice = 4.833540085511818m,
                            UnitsInStock = 25
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 3,
                            ProductName = "Small Fresh Sausages",
                            UnitPrice = 33.602891454679645m,
                            UnitsInStock = 22
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 6,
                            ProductName = "Tasty Rubber Car",
                            UnitPrice = 23.452640416561465m,
                            UnitsInStock = 25
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 4,
                            ProductName = "Gorgeous Rubber Cheese",
                            UnitPrice = 63.517997681240563m,
                            UnitsInStock = 31
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 6,
                            ProductName = "Generic Wooden Sausages",
                            UnitPrice = 29.001366292319695m,
                            UnitsInStock = 93
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            ProductName = "Licensed Rubber Gloves",
                            UnitPrice = 2.7736663814732863m,
                            UnitsInStock = 45
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 1,
                            ProductName = "Handcrafted Fresh Towels",
                            UnitPrice = 1.34408392491627154m,
                            UnitsInStock = 85
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 2,
                            ProductName = "Generic Soft Gloves",
                            UnitPrice = 52.704623908666729m,
                            UnitsInStock = 21
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 2,
                            ProductName = "Handcrafted Steel Cheese",
                            UnitPrice = 73.526593828228705m,
                            UnitsInStock = 99
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            ProductName = "Handcrafted Granite Salad",
                            UnitPrice = 24.77302135288795m,
                            UnitsInStock = 6
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 4,
                            ProductName = "Generic Fresh Ball",
                            UnitPrice = 84.281817130317091m,
                            UnitsInStock = 63
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            ProductName = "Small Rubber Car",
                            UnitPrice = 27.10452600518158m,
                            UnitsInStock = 73
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 4,
                            ProductName = "Small Rubber Bike",
                            UnitPrice = 39.485646756180613m,
                            UnitsInStock = 85
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            ProductName = "Licensed Steel Cheese",
                            UnitPrice = 82.071196227610435m,
                            UnitsInStock = 46
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 1,
                            ProductName = "Ergonomic Rubber Table",
                            UnitPrice = 29.728922499469027m,
                            UnitsInStock = 88
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 8,
                            ProductName = "Awesome Plastic Chair",
                            UnitPrice = 84.04858062421426m,
                            UnitsInStock = 96
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 6,
                            ProductName = "Tasty Wooden Gloves",
                            UnitPrice = 59.70951097731478m,
                            UnitsInStock = 34
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 3,
                            ProductName = "Generic Concrete Keyboard",
                            UnitPrice = 29.469358463052925m,
                            UnitsInStock = 52
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 7,
                            ProductName = "Handmade Soft Ball",
                            UnitPrice = 90.58719175750432m,
                            UnitsInStock = 55
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 1,
                            ProductName = "Gorgeous Rubber Table",
                            UnitPrice = 51.795613139337649m,
                            UnitsInStock = 61
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 5,
                            ProductName = "Ergonomic Rubber Gloves",
                            UnitPrice = 82.237695564092518m,
                            UnitsInStock = 2
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 8,
                            ProductName = "Incredible Granite Hat",
                            UnitPrice = 60.594259471050799m,
                            UnitsInStock = 5
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 3,
                            ProductName = "Refined Rubber Soap",
                            UnitPrice = 56.506641762912769m,
                            UnitsInStock = 22
                        });
                });

            modelBuilder.Entity("Repository.entities.Product", b =>
                {
                    b.HasOne("Repository.entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Repository.entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
